[package]
edition = "2021"
name = "cw-band"
version = "0.1.0-alpha.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.1.5"
cosmwasm-std = {version = "1.1.5", features = ["ibc3"]}
obi = "0.0.2"
