[package]
edition = "2021"
name = "band"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = {version = "1.0.0", features = ["ibc3"]}
obi = "0.0.2"
schemars = "0.8.8"
serde = {version = "1.0.137", default-features = false, features = ["derive"]}
